### ISSUE TITLE
bazel无法build OpenCV

### ISSUE THREAD

**Issue by Yang-YiFan** [ponyai/PublicCourse#11]
我的opencv静态链接库并不在`/usr/lib/x86_64-linux-gnu`中，所以我修改了`WORKSPACE`以及`/utils/bazel/opencv.BUILD`中所有的路径，改为了我自己机器上opencv静态链接库的路径。但是在使用bazel build时仍然出现了错误，
`homework3/chessboard/BUILD:3:1: undeclared inclusion(s) in rule '//homework3/chessboard:opencv_example':
this rule is missing dependency declarations for the following files included by 'homework3/chessboard/opencv_example.cc':
  '/usr/local/include/opencv2/core/core.hpp'
  '/usr/local/include/opencv2/core.hpp'
`后面还有许多行显示include文件我就没有粘贴。请问如何解决？谢谢！

**Comment by ponyai-lyc** [comment]
@Yang-YiFan 我这里重现你的问题稍微有一点困难。一个比较简单的办法可能是从现在安装的位置到目标位置建一个软链。比如`ln -s /path/to/folderA /path/to/folderB` 会生成一个假的folderB，在实际被调用的时候会自动到folderA寻找。你可以尝试一下这个办法能不能很快的帮助你解决问题。如果还是不可以的话我这边会尝试配置一下～

**Comment by Yang-YiFan** [comment]
我用ln -s将需要的.so文件链接到了指定位置，恢复了原本的`WORKSPACE`和`/utils/bazel/opencv.BUILD`中的路径，但是出现了`ERROR: circular symlinks detected
[start of symlink cycle]
/usr/lib/x86_64-linux-gnu/libopencv_core.so
[end of symlink cycle]`的错误，我再次将这个.so文件从`/usr/lib/x86_64-linux-gnu/`中移除，就又会出现原本的`ERROR: missing input file '@opencv//:lib/x86_64-linux-gnu/libopencv_core.so'`错误。
我这里使用cmake是可以正常编译运行opencv的相关程序的，请问我们的作业和之后的大作业必须使用bazel来build opencv么？

**Comment by jcvbcn** [comment]
我之前也遇到了这个问题。把opencv卸了之后重新用apt-get装似乎就好了。

**Comment by Yang-YiFan** [comment]
感谢 @jcvbcn 提供的办法，我使用`sudo apt-get install libcv-dev`解决了问题。
