### ISSUE TITLE
Homework5的问题

### ISSUE THREAD

**Issue by Yang-YiFan** [ponyai/PublicCourse#13]
我在自己的机器上运行所给的map viewer时出现了形如下图的错误
![_20180407183128](https://user-images.githubusercontent.com/22767536/38454025-17f43fee-3a92-11e8-99db-09209f3466ac.png)
我这里map的central line和left bound and right bound是分离开的，central line是在grid上静止的，并且悬浮的left bound and right bound可以自由旋转移动....不能复现出与所提供的map viewer截图一样的场景，请问如何解决？

**Comment by xuan-pony** [comment]
@Yang-YiFan 

同学你好，很抱歉给你带来了困扰。我在我本地的Ubuntu，或者一个装有Ubuntu16.04的全新的VirtualBox虚拟机中都无法复现你的错误。能否请你提供一些更多的信息？

1. 你的Ubuntu版本信息，以及运行命令`glxinfo | grep "OpenGL version"`返回的OpenGL版本信息？ 
2. 你运行的时候是否修改过任何源代码？
3. 你的同学是否遇到了一样的问题？

**Comment by Yang-YiFan** [comment]
我用的也是Ubuntu16.04虚拟机，OpenGL信息是`OpenGL version string: 3.0 Mesa 17.2.8`。我没有修改过源代码，是直接运行的给的作业的代码。

**Comment by adrenaline21** [comment]
帮同学提一下，这里也有相同的问题

**Comment by neetenin** [comment]
I also have this problem.

**Comment by xuan-pony** [comment]
@neetenin 

非常抱歉因为代码的兼容性给大家做作业带来了麻烦。因为这个问题公司里的同事都没能复现出来，所以没有办法很快的给出解决方案。明天上课的时候，我会去学校帮大家现场看一下，看能不能找到解决问题的办法。
