### ISSUE TITLE
Problems on Perception Project

### ISSUE THREAD

**Issue by ldf921** [ponyai/PublicCourse#15]
Hi everyone,

In the readme of perception project, it said that fusing camera image to provide extra information for the perception project is **optional**. So how do you evaluate the project? Will you compute the precision and recall metrics with or without providing camera image? Will you evaluate the methods in both settings and combine the result in some way?

Tingfung

**Comment by boconglpony** [comment]
Hi Tingfung,

Thanks for your question.
To clarify, the only thing we will evaluate is the overall Lidar detection (mainly focus on the segmentation) precision and recall, which has been mention in lecture. You can make use the dense feature, such as color and texture, which can be extracted from those camera images to improve your Lidar detection method. 

The evaluation framework will evaluate in the same way no matter you use camera image or not. Hope this can answer your question.

Thanks,
Bocong Liu
