### ISSUE TITLE
Homework2的一些问题

### ISSUE THREAD

**Issue by hzaskywalker** [ponyai/PublicCourse#3]
1.  try to visualize算不算作业？
2. 是不是一定要用bazel+C++来实现？
3. 大部分任务都没有明确的评测标准，所以是只要在合理的范围内看起来差不多就行了？
4. 给定的数据没有相对应的说明，是不是可以认为image就是指的data里的那些jpg文件而不是其它神奇的东西？
5. ground, lane bounderies和land marks是啥？

**Comment by boconglpony** [comment]
Hi hazskywalker,
非常感谢你的反馈。对我们的描述不周，非常抱歉。

1. 不算作业，我又更新了readme，明确了每个task要交的内容。
2. 如上。
4. 是的，已经再样例数据包里加了readme。
5. 请看readme。 关于ground也加了两张样例图。

Thanks,
Bocong Liu

**Comment by Yang-YiFan** [comment]
请问visualize一定要用c++实现么？

**Comment by boconglpony** [comment]
Hi @Yang-YiFan 
不需要的。 我们接下来也会提供一个c++的可视化工具给大家。大家可以选择使用。
Thanks,
Bocong Liu

**Comment by Chenyao2333** [comment]
@boconglpony 什么时候可以提供可视化工具呢？谢谢(｡･∀･)ﾉﾞ

**Comment by boconglpony** [comment]
Hi @Chenyao2333 

Sorry about the delay. Use can use the viewer in Homework4 to visualize the pointcloud:
https://github.com/ponyai/PublicCourse/tree/master/homework4

Thanks,
Bocong Liu
