### ISSUE TITLE
Error in Homework2 

### ISSUE THREAD

**Issue by aviczhl2** [ponyai/PublicCourse#4]
I first extracted sample_data.tar.gz, then run the code

bazel run -c opt //homework2:main 

in directory "PublicCourse", as the README guided.

But it still shows the following error message 

INFO: Analysed target //homework2:main (0 packages loaded).
INFO: Found 1 target...
Target //homework2:main up-to-date:
  bazel-bin/homework2/main
INFO: Elapsed time: 0.621s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/homework2/main
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0311 21:54:11.103610 74108 pointcloud.cc:11] Check failed: file != nullptr Fail to open file /PublicCourse/homework2/sample_data/VelodyneDevice32c/0.txt
*** Check failure stack trace: ***

So why does this happen?

**Comment by zrt** [comment]
https://github.com/ponyai/PublicCourse/blob/a184b4b835be52efa89439fa93c24ae1d828e466/homework2/main.cc#L8

尝试修改一下路径：
https://github.com/ponyai/PublicCourse/blob/a184b4b835be52efa89439fa93c24ae1d828e466/homework2/main.cc#L10

或者尝试`ln -s`命令。

**Comment by aviczhl2** [comment]
I noticed that, thanks.

**Comment by boconglpony** [comment]
Hi @aviczhl2,

Is your issue solved?

Thanks,
Bocong Liu

**Comment by aviczhl2** [comment]
Yes, you can close that.
