### ISSUE TITLE
Homework2 的另一些问题

### ISSUE THREAD

**Issue by Chenyao2333** [ponyai/PublicCourse#5]
## Task1

提示表明一定要用C++画直方图。为什么这些任务不可以使用统计数据较为方便的Python 等语言？

## Task 3

我可以使用OpenCV 接口来读取png/jpg格式的RBG值，然后再手动转换吗？

**Comment by boconglpony** [comment]
Hi @Chenyao2333 

Sorry for the late reply.

For your first question, you can use python for plotting the histogram. I will update the homework requirement.
For your second question, yes, you can use OpenCV to read the RGB image and convert it to grey scale by yourself.

Thanks,
Bocong Liu

**Comment by Chenyao2333** [comment]
@boconglpony 
Got it.
Thanks for your reply.
