### ISSUE TITLE
Homework3的一些问题

### ISSUE THREAD

**Issue by hqztrue** [ponyai/PublicCourse#6]
1. rotation/rotation_test.cc的第38行似应为EXPECT_NEAR(1.0, angle_axis.axis().norm(), 3e-2);
2. 第一题可以使用eigen的内置转换函数么？还是要自己实现

**Comment by boconglpony** [comment]
hi @hqztrue ,
1. 不好意思，已经修正了。
2. 需要自己实现，主要是考察对rotation matrix和axis angle数学表达的理解。

**Comment by hqztrue** [comment]
辛苦楼上了;
1. 38行似只修正了1/3
2. 关于第一题的AngleAxisTest，易知给定的Matrix3d rotation不为合法的旋转矩阵：(matlab code)
M=[0.99505412, -0.03004994, 0.01981681;0.02985011, 0.995204, 0.01028309;-0.02011656, -0.00968359, 0.99545379]
all(abs(inv(M)-M')<0.001)
这违反了旋转矩阵必为正交矩阵的性质。

**Comment by boconglpony** [comment]
Hi @hqztrue Thanks for the feedback.

@ponyai-lyc Could you please take a look?

**Comment by ponyai-lyc** [comment]
Hi @hqztrue , thanks a lot for pointing out that. The current matrix should be fine.

**Comment by hqztrue** [comment]
@ponyai-lyc 那么请问修正了rotation matrix之后，AngleAxisTest的标准答案发生改变了吗？
Eigen::AngleAxisd d;
d.fromRotationMatrix(rotation);
printf("%.5lf %.5lf %.5lf %.5lf\n",d.angle(), d.axis().x(), d.axis().y(), d.axis().z());
用以上eigen提供的函数检验，输出为0.03752 -0.26726 0.53452 0.80178，与我的答案相符，但旋转角不为0.1。

**Comment by ponyai-lyc** [comment]
@hqztrue 感谢你验算了结果。我double check一下哈。我的理解是设置数据的时候因为旋转角度太小，导致精度不够，误差就会比较大。

**Comment by Chenyao2333** [comment]
@ponyai-lyc 我发现RollPitchYawTest 中的矩阵是通过R_x(0.3)*R_y(-0.2)*R_z(0.1)得来的。

代码是用来验证如何得到Test中的矩阵的。

```
#include "Eigen/Core"
#include "Eigen/Geometry"

#include <iostream>

using namespace std;
using namespace Eigen;

int main() {
    Matrix3d m, r;
    m = AngleAxisd(0.3, Vector3d::UnitX()).toRotationMatrix()
      * AngleAxisd(-0.2, Vector3d::UnitY()).toRotationMatrix()
      * AngleAxisd(0.1, Vector3d::UnitZ()).toRotationMatrix();


    r<< 0.97517033, -0.0978434, -0.19866933,
        0.03695701, 0.95642509, -0.28962948,
        0.21835066, 0.27509585, 0.93629336;
    
    cout << m << endl;
    cout << "====" << endl;
    cout << r << endl;
    cout << "====" << endl;
    cout << r.eulerAngles(0, 1, 2) << endl;;
    return 0;
}
```

但是我认为你期望得到的数据是R_z(0.3)*R_y(-0.2)*R_x(0.1)或者R_z(0.1)*R_y(-0.2)*R_x(0.3)。不知道这里是错误还是出于什么考虑？

**Comment by ponyai-lyc** [comment]
@Chenyao2333 多谢你指出这个问题，是我错了T.T，马上会更正。
