### ISSUE TITLE
Cannot Work with the Current Workspace

### ISSUE THREAD

**Issue by aviczhl2** [ponyai/PublicCourse#8]
I pulled the newest version of the code, but it does not work, even with the helloworld at the very beginning.

Is there some problems about the workspace change or sth.?

INFO: Analysed target //homework1/helloworld:main (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/xuzou/PublicCourse/homework1/helloworld/BUILD:3:1: C++ compilation of rule '//homework1/helloworld:main' failed (Exit 1)
src/main/tools/linux-sandbox-pid1.cc:427: "execvp(/usr/bin/clang-3.8, 0x13794b0)": No such file or directory
Target //homework1/helloworld:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.876s, Critical Path: 0.09s
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target

**Comment by DonaldScrump** [comment]
As the error info goes, you need to install clang. 
`sudo apt-get install clang`
I ran into the same problem with a fresh Ubuntu, but was fine after installing clang-3.8

**Comment by xuan-pony** [comment]
@aviczhl2 Sorry for the trouble. Please install `clang-3.8` and other dependencies specified in README.md. 
```
sudo apt install qtdeclarative5-dev clang-3.8 nasm
```
